// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inqueue_touch.sql

package lrdb

import (
	"context"

	"github.com/google/uuid"
)

const touchInqueueWork = `-- name: TouchInqueueWork :exec
UPDATE inqueue
SET
  claimed_at = NOW()
WHERE
  id IN ($1::uuid[])
  AND claimed_by = $2
`

type TouchInqueueWorkParams struct {
	Ids       []uuid.UUID `json:"ids"`
	ClaimedBy int64       `json:"claimed_by"`
}

func (q *Queries) TouchInqueueWork(ctx context.Context, arg TouchInqueueWorkParams) error {
	_, err := q.db.Exec(ctx, touchInqueueWork, arg.Ids, arg.ClaimedBy)
	return err
}
