// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inqueue_put.sql

package lrdb

import (
	"context"

	"github.com/google/uuid"
)

const putInqueueWork = `-- name: PutInqueueWork :exec
INSERT INTO inqueue (organization_id, collector_name, instance_num, bucket, object_id, signal, priority, file_size)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type PutInqueueWorkParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CollectorName  string    `json:"collector_name"`
	InstanceNum    int16     `json:"instance_num"`
	Bucket         string    `json:"bucket"`
	ObjectID       string    `json:"object_id"`
	Signal         string    `json:"signal"`
	Priority       int32     `json:"priority"`
	FileSize       int64     `json:"file_size"`
}

func (q *Queries) PutInqueueWork(ctx context.Context, arg PutInqueueWorkParams) error {
	_, err := q.db.Exec(ctx, putInqueueWork,
		arg.OrganizationID,
		arg.CollectorName,
		arg.InstanceNum,
		arg.Bucket,
		arg.ObjectID,
		arg.Signal,
		arg.Priority,
		arg.FileSize,
	)
	return err
}
