// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcq_touch.sql

package lrdb

import (
	"context"
)

const touchMetricCompactionWork = `-- name: TouchMetricCompactionWork :exec
UPDATE metric_compaction_queue
SET
  claimed_at = NOW(),
  heartbeated_at = NOW()
WHERE
  id = ANY($1::bigint[])
  AND claimed_by = $2
`

type TouchMetricCompactionWorkParams struct {
	Ids       []int64 `json:"ids"`
	ClaimedBy int64   `json:"claimed_by"`
}

func (q *Queries) TouchMetricCompactionWork(ctx context.Context, arg TouchMetricCompactionWorkParams) error {
	_, err := q.db.Exec(ctx, touchMetricCompactionWork, arg.Ids, arg.ClaimedBy)
	return err
}
