// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mcq_put.sql

package lrdb

import (
	"context"

	"github.com/google/uuid"
)

const putMetricCompactionWork = `-- name: PutMetricCompactionWork :exec
INSERT INTO metric_compaction_queue (
  organization_id,
  dateint,
  frequency_ms,
  segment_id,
  instance_num,
  record_count,
  priority
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type PutMetricCompactionWorkParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Dateint        int32     `json:"dateint"`
	FrequencyMs    int64     `json:"frequency_ms"`
	SegmentID      int64     `json:"segment_id"`
	InstanceNum    int16     `json:"instance_num"`
	RecordCount    int64     `json:"record_count"`
	Priority       int32     `json:"priority"`
}

func (q *Queries) PutMetricCompactionWork(ctx context.Context, arg PutMetricCompactionWorkParams) error {
	_, err := q.db.Exec(ctx, putMetricCompactionWork,
		arg.OrganizationID,
		arg.Dateint,
		arg.FrequencyMs,
		arg.SegmentID,
		arg.InstanceNum,
		arg.RecordCount,
		arg.Priority,
	)
	return err
}
