// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mrq_put.sql

package lrdb

import (
	"context"

	"github.com/google/uuid"
)

const putMetricRollupWork = `-- name: PutMetricRollupWork :exec
INSERT INTO metric_rollup_queue (
  organization_id,
  dateint,
  frequency_ms,
  instance_num,
  slot_id,
  slot_count,
  priority
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
`

type PutMetricRollupWorkParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Dateint        int32     `json:"dateint"`
	FrequencyMs    int64     `json:"frequency_ms"`
	InstanceNum    int16     `json:"instance_num"`
	SlotID         int32     `json:"slot_id"`
	SlotCount      int32     `json:"slot_count"`
	Priority       int32     `json:"priority"`
}

func (q *Queries) PutMetricRollupWork(ctx context.Context, arg PutMetricRollupWorkParams) error {
	_, err := q.db.Exec(ctx, putMetricRollupWork,
		arg.OrganizationID,
		arg.Dateint,
		arg.FrequencyMs,
		arg.InstanceNum,
		arg.SlotID,
		arg.SlotCount,
		arg.Priority,
	)
	return err
}
