version: 2

project_name: lakerunner

before:
  hooks:
    - make generate
    - go test -race ./...

partial:
  by: target

checksum:
  name_template: "checksums.txt"

release:
  disable: true

changelog:
  disable: true

archives:
  - id: default
    # use the "binary" format so GoReleaser skips creating an archive
    formats:
      - binary

builds:
  - id: lakerunner
    main: ./main.go
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      #- -extldflags "-lc -lrt -lpthread --static"
      - -X main.commit={{ .Commit }}
      - -X main.version={{ .Version }}
    flags:
      - -trimpath

# Define how to build/push Docker images.
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    context: .
    use: buildx
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:v{{ .Version }}-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner:latest-amd64"
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --build-arg=DUCKDB_SDK_VERSION={{ if .Env.DUCKDB_SDK_VERSION }}{{ .Env.DUCKDB_SDK_VERSION }}{{ else }}latest{{ end }}
      - --build-arg=TARGETARCH=amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    context: .
    use: buildx
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:v{{ .Version }}-arm64"
      - "public.ecr.aws/cardinalhq.io/lakerunner:latest-arm64"
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --build-arg=DUCKDB_SDK_VERSION={{ if .Env.DUCKDB_SDK_VERSION }}{{ .Env.DUCKDB_SDK_VERSION }}{{ else }}latest{{ end }}
      - --build-arg=TARGETARCH=arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
docker_manifests:
  - name_template: "public.ecr.aws/cardinalhq.io/lakerunner:v{{ .Version }}"
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:v{{ .Version }}-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner:v{{ .Version }}-arm64"
  - name_template: "public.ecr.aws/cardinalhq.io/lakerunner:latest"
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:latest-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner:latest-arm64"
