version: 2

before:
  hooks:
    - make generate
    - go test -race ./...

release:
  disable: true

changelog:
  disable: true

archives:
  - id: default
    # use the "binary" format so GoReleaser skips creating an archive
    formats:
      - binary

builds:
  - id: lakerunner
    main: ./main.go
    binary: lakerunner
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.commit={{ .Commit }}
      - -X main.version={{ .Version }}
    flags:
      - -trimpath

# Define how to build/push Docker images.
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:v{{ .Version }}-amd64"
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:latest-dev-amd64"
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:v{{ .Version }}-arm64"
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:latest-dev-arm64"
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
docker_manifests:
  - name_template: "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:v{{ .Version }}"
    image_templates:
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:v{{ .Version }}-amd64"
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:v{{ .Version }}-arm64"
  - name_template: "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:latest-dev"
    image_templates:
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:latest-dev-amd64"
      - "033263751764.dkr.ecr.us-east-2.amazonaws.com/cardinalhq/lakerunner:latest-dev-arm64"
