version: 2

project_name: lakerunner

before:
  hooks:
    - go mod tidy

partial:
  by: target

checksum:
  name_template: "checksums.txt"

release:
  disable: true

changelog:
  disable: true

archives:
  - id: default
    # use the "binary" format so GoReleaser skips creating an archive
    formats:
      - binary

builds:
  - id: lakerunner
    main: ./main.go
    binary: lakerunner
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cardinalhq/lakerunner/cmd.Version={{.Version}}
      - -X github.com/cardinalhq/lakerunner/cmd.Commit={{.Commit}}
      - -X github.com/cardinalhq/lakerunner/cmd.Date={{.Date}}
  - id: lakectl
    main: ./lakectl/main.go
    binary: lakectl
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cardinalhq/lakerunner/lakectl/cmd.Version={{.Version}}
      - -X github.com/cardinalhq/lakerunner/lakectl/cmd.Commit={{.Commit}}
      - -X github.com/cardinalhq/lakerunner/lakectl/cmd.Date={{.Date}}

# Define how to build/push Docker images.
# Only creates the exact tag provided - no additional tags
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    ids:
      - lakerunner
      - lakectl
    extra_files:
      - docker/duckdb-extensions
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:{{ .Tag }}-amd64"
    build_flag_templates:
      - --pull
      - --no-cache
      - --platform=linux/amd64
      - --provenance=false
      - --sbom=false
      - --build-arg=TARGETARCH=amd64
      - --build-arg=DUCKDB_VERSION=v1.3.2
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    ids:
      - lakerunner
      - lakectl
    extra_files:
      - docker/duckdb-extensions
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:{{ .Tag }}-arm64"
    build_flag_templates:
      - --pull
      - --no-cache
      - --platform=linux/arm64
      - --provenance=false
      - --sbom=false
      - --build-arg=TARGETARCH=arm64
      - --build-arg=DUCKDB_VERSION=v1.3.2
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}

docker_manifests:
  - name_template: "public.ecr.aws/cardinalhq.io/lakerunner:{{ .Tag }}"
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner:{{ .Tag }}-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner:{{ .Tag }}-arm64"
