header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: CardinalHQ, Inc
    copyright-year: 2025

  paths-ignore:
    - 'bin'
    - 'buildtime'
    - '**/*.md'
    - 'NOTICE'
    - 'LICENSE'
    - .gitignore
    - .dockerignore
    - .github
    - .licenserc.yaml
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.json'
    - '**/*.mermaid'
    - go.sum
    - go.mod
    - go.work
    - go.work.sum
    - '**/testdata/**'
    - .idea
    - '**/*.sql.go'
    - '**/*.sql'
    - pkg/*db/batch.go
    - pkg/*db/db.go
    - pkg/*db/models.go
    - pkg/*db/querier.go
    - pkg/*db/copyfrom.go
    - internal/configdb/batch.go
    - internal/configdb/db.go
    - internal/configdb/models.go
    - internal/configdb/querier.go
    - internal/configdb/copyfrom.go

  comment: on-failure
