// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: org_config.sql

package configdb

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteOrgConfig = `-- name: DeleteOrgConfig :exec
DELETE FROM organization_config
WHERE organization_id = $1 AND key = $2
`

type DeleteOrgConfigParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Key            string    `json:"key"`
}

// Delete a specific config for an org.
func (q *Queries) DeleteOrgConfig(ctx context.Context, arg DeleteOrgConfigParams) error {
	_, err := q.db.Exec(ctx, deleteOrgConfig, arg.OrganizationID, arg.Key)
	return err
}

const getOrgConfig = `-- name: GetOrgConfig :one
SELECT value
FROM organization_config
WHERE organization_id = $1 AND key = $2
`

type GetOrgConfigParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Key            string    `json:"key"`
}

// Get config for a specific org and key. Returns NULL if not found.
func (q *Queries) GetOrgConfig(ctx context.Context, arg GetOrgConfigParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getOrgConfig, arg.OrganizationID, arg.Key)
	var value json.RawMessage
	err := row.Scan(&value)
	return value, err
}

const getOrgConfigWithDefault = `-- name: GetOrgConfigWithDefault :one
SELECT COALESCE(
    (SELECT oc1.value FROM organization_config oc1 WHERE oc1.organization_id = $1 AND oc1.key = $2),
    (SELECT oc2.value FROM organization_config oc2 WHERE oc2.organization_id = '00000000-0000-0000-0000-000000000000' AND oc2.key = $2)
) AS config_value
`

type GetOrgConfigWithDefaultParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Key            string    `json:"key"`
}

// Get config for org, falling back to system default (nil UUID) if not found.
func (q *Queries) GetOrgConfigWithDefault(ctx context.Context, arg GetOrgConfigWithDefaultParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getOrgConfigWithDefault, arg.OrganizationID, arg.Key)
	var config_value interface{}
	err := row.Scan(&config_value)
	return config_value, err
}

const listOrgConfigs = `-- name: ListOrgConfigs :many
SELECT key, value, created_at, updated_at
FROM organization_config
WHERE organization_id = $1
ORDER BY key
`

type ListOrgConfigsRow struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	CreatedAt time.Time       `json:"created_at"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// List all config keys/values for an org.
func (q *Queries) ListOrgConfigs(ctx context.Context, organizationID uuid.UUID) ([]ListOrgConfigsRow, error) {
	rows, err := q.db.Query(ctx, listOrgConfigs, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgConfigsRow
	for rows.Next() {
		var i ListOrgConfigsRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgConfig = `-- name: UpsertOrgConfig :exec
INSERT INTO organization_config (organization_id, key, value, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (organization_id, key)
DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertOrgConfigParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	Key            string          `json:"key"`
	Value          json.RawMessage `json:"value"`
}

// Insert or update a config value for an org.
func (q *Queries) UpsertOrgConfig(ctx context.Context, arg UpsertOrgConfigParams) error {
	_, err := q.db.Exec(ctx, upsertOrgConfig, arg.OrganizationID, arg.Key, arg.Value)
	return err
}
