// Copyright (C) 2025 CardinalHQ, Inc
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, version 3.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: queryworker.proto

package queryproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushDownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	BaseExpr       *BaseExpr              `protobuf:"bytes,2,opt,name=base_expr,json=baseExpr,proto3" json:"base_expr,omitempty"`
	StartTs        int64                  `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs          int64                  `protobuf:"varint,4,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	StepDurationMs int64                  `protobuf:"varint,5,opt,name=step_duration_ms,json=stepDurationMs,proto3" json:"step_duration_ms,omitempty"` // Duration in milliseconds
	Segments       []*SegmentInfo         `protobuf:"bytes,6,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushDownRequest) Reset() {
	*x = PushDownRequest{}
	mi := &file_queryworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushDownRequest) ProtoMessage() {}

func (x *PushDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushDownRequest.ProtoReflect.Descriptor instead.
func (*PushDownRequest) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{0}
}

func (x *PushDownRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *PushDownRequest) GetBaseExpr() *BaseExpr {
	if x != nil {
		return x.BaseExpr
	}
	return nil
}

func (x *PushDownRequest) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *PushDownRequest) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *PushDownRequest) GetStepDurationMs() int64 {
	if x != nil {
		return x.StepDurationMs
	}
	return 0
}

func (x *PushDownRequest) GetSegments() []*SegmentInfo {
	if x != nil {
		return x.Segments
	}
	return nil
}

type BaseExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Matchers      []*LabelMatch          `protobuf:"bytes,3,rep,name=matchers,proto3" json:"matchers,omitempty"`
	Range         string                 `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	SubqueryStep  string                 `protobuf:"bytes,5,opt,name=subquery_step,json=subqueryStep,proto3" json:"subquery_step,omitempty"`
	Offset        string                 `protobuf:"bytes,6,opt,name=offset,proto3" json:"offset,omitempty"`
	GroupBy       []string               `protobuf:"bytes,7,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Without       []string               `protobuf:"bytes,8,rep,name=without,proto3" json:"without,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseExpr) Reset() {
	*x = BaseExpr{}
	mi := &file_queryworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseExpr) ProtoMessage() {}

func (x *BaseExpr) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseExpr.ProtoReflect.Descriptor instead.
func (*BaseExpr) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{1}
}

func (x *BaseExpr) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseExpr) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *BaseExpr) GetMatchers() []*LabelMatch {
	if x != nil {
		return x.Matchers
	}
	return nil
}

func (x *BaseExpr) GetRange() string {
	if x != nil {
		return x.Range
	}
	return ""
}

func (x *BaseExpr) GetSubqueryStep() string {
	if x != nil {
		return x.SubqueryStep
	}
	return ""
}

func (x *BaseExpr) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *BaseExpr) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *BaseExpr) GetWithout() []string {
	if x != nil {
		return x.Without
	}
	return nil
}

type LabelMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // Matches the type field from promql.LabelMatch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelMatch) Reset() {
	*x = LabelMatch{}
	mi := &file_queryworker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelMatch) ProtoMessage() {}

func (x *LabelMatch) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelMatch.ProtoReflect.Descriptor instead.
func (*LabelMatch) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{2}
}

func (x *LabelMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabelMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LabelMatch) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SegmentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateInt       int32                  `protobuf:"varint,1,opt,name=date_int,json=dateInt,proto3" json:"date_int,omitempty"`
	Hour          string                 `protobuf:"bytes,2,opt,name=hour,proto3" json:"hour,omitempty"`
	SegmentId     string                 `protobuf:"bytes,3,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	StartTs       int64                  `protobuf:"varint,4,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	EndTs         int64                  `protobuf:"varint,5,opt,name=end_ts,json=endTs,proto3" json:"end_ts,omitempty"`
	ExprId        string                 `protobuf:"bytes,6,opt,name=expr_id,json=exprId,proto3" json:"expr_id,omitempty"`
	Dataset       string                 `protobuf:"bytes,7,opt,name=dataset,proto3" json:"dataset,omitempty"`
	BucketName    string                 `protobuf:"bytes,8,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	CustomerId    string                 `protobuf:"bytes,9,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CollectorId   string                 `protobuf:"bytes,10,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Frequency     int64                  `protobuf:"varint,11,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentInfo) Reset() {
	*x = SegmentInfo{}
	mi := &file_queryworker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentInfo) ProtoMessage() {}

func (x *SegmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentInfo.ProtoReflect.Descriptor instead.
func (*SegmentInfo) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{3}
}

func (x *SegmentInfo) GetDateInt() int32 {
	if x != nil {
		return x.DateInt
	}
	return 0
}

func (x *SegmentInfo) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *SegmentInfo) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *SegmentInfo) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *SegmentInfo) GetEndTs() int64 {
	if x != nil {
		return x.EndTs
	}
	return 0
}

func (x *SegmentInfo) GetExprId() string {
	if x != nil {
		return x.ExprId
	}
	return ""
}

func (x *SegmentInfo) GetDataset() string {
	if x != nil {
		return x.Dataset
	}
	return ""
}

func (x *SegmentInfo) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *SegmentInfo) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SegmentInfo) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *SegmentInfo) GetFrequency() int64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type SketchInputResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*SketchInputResponse_Data
	//	*SketchInputResponse_Error
	//	*SketchInputResponse_Done
	Response      isSketchInputResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchInputResponse) Reset() {
	*x = SketchInputResponse{}
	mi := &file_queryworker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchInputResponse) ProtoMessage() {}

func (x *SketchInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchInputResponse.ProtoReflect.Descriptor instead.
func (*SketchInputResponse) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{4}
}

func (x *SketchInputResponse) GetResponse() isSketchInputResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *SketchInputResponse) GetData() *SketchInput {
	if x != nil {
		if x, ok := x.Response.(*SketchInputResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *SketchInputResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*SketchInputResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SketchInputResponse) GetDone() *CompletionResponse {
	if x != nil {
		if x, ok := x.Response.(*SketchInputResponse_Done); ok {
			return x.Done
		}
	}
	return nil
}

type isSketchInputResponse_Response interface {
	isSketchInputResponse_Response()
}

type SketchInputResponse_Data struct {
	Data *SketchInput `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type SketchInputResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type SketchInputResponse_Done struct {
	Done *CompletionResponse `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

func (*SketchInputResponse_Data) isSketchInputResponse_Response() {}

func (*SketchInputResponse_Error) isSketchInputResponse_Response() {}

func (*SketchInputResponse_Done) isSketchInputResponse_Response() {}

type SketchInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExprId         string                 `protobuf:"bytes,1,opt,name=expr_id,json=exprId,proto3" json:"expr_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Timestamp      int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Frequency      int64                  `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"` // in seconds
	SketchTags     *SketchTags            `protobuf:"bytes,5,opt,name=sketch_tags,json=sketchTags,proto3" json:"sketch_tags,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SketchInput) Reset() {
	*x = SketchInput{}
	mi := &file_queryworker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchInput) ProtoMessage() {}

func (x *SketchInput) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchInput.ProtoReflect.Descriptor instead.
func (*SketchInput) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{5}
}

func (x *SketchInput) GetExprId() string {
	if x != nil {
		return x.ExprId
	}
	return ""
}

func (x *SketchInput) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SketchInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SketchInput) GetFrequency() int64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *SketchInput) GetSketchTags() *SketchTags {
	if x != nil {
		return x.SketchTags
	}
	return nil
}

type SketchTags struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of tag key-value pairs
	Tags          map[string]string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SketchTags) Reset() {
	*x = SketchTags{}
	mi := &file_queryworker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SketchTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SketchTags) ProtoMessage() {}

func (x *SketchTags) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SketchTags.ProtoReflect.Descriptor instead.
func (*SketchTags) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{6}
}

func (x *SketchTags) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_queryworker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{7}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_queryworker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{8}
}

func (x *CompletionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_queryworker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_queryworker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queryworker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_queryworker_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_queryworker_proto protoreflect.FileDescriptor

const file_queryworker_proto_rawDesc = "" +
	"\n" +
	"\x11queryworker.proto\x12\n" +
	"queryproto\"\xfe\x01\n" +
	"\x0fPushDownRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x121\n" +
	"\tbase_expr\x18\x02 \x01(\v2\x14.queryproto.BaseExprR\bbaseExpr\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x04 \x01(\x03R\x05endTs\x12(\n" +
	"\x10step_duration_ms\x18\x05 \x01(\x03R\x0estepDurationMs\x123\n" +
	"\bsegments\x18\x06 \x03(\v2\x17.queryproto.SegmentInfoR\bsegments\"\xee\x01\n" +
	"\bBaseExpr\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x122\n" +
	"\bmatchers\x18\x03 \x03(\v2\x16.queryproto.LabelMatchR\bmatchers\x12\x14\n" +
	"\x05range\x18\x04 \x01(\tR\x05range\x12#\n" +
	"\rsubquery_step\x18\x05 \x01(\tR\fsubqueryStep\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\tR\x06offset\x12\x19\n" +
	"\bgroup_by\x18\a \x03(\tR\agroupBy\x12\x18\n" +
	"\awithout\x18\b \x03(\tR\awithout\"J\n" +
	"\n" +
	"LabelMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xc3\x02\n" +
	"\vSegmentInfo\x12\x19\n" +
	"\bdate_int\x18\x01 \x01(\x05R\adateInt\x12\x12\n" +
	"\x04hour\x18\x02 \x01(\tR\x04hour\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x03 \x01(\tR\tsegmentId\x12\x19\n" +
	"\bstart_ts\x18\x04 \x01(\x03R\astartTs\x12\x15\n" +
	"\x06end_ts\x18\x05 \x01(\x03R\x05endTs\x12\x17\n" +
	"\aexpr_id\x18\x06 \x01(\tR\x06exprId\x12\x18\n" +
	"\adataset\x18\a \x01(\tR\adataset\x12\x1f\n" +
	"\vbucket_name\x18\b \x01(\tR\n" +
	"bucketName\x12\x1f\n" +
	"\vcustomer_id\x18\t \x01(\tR\n" +
	"customerId\x12!\n" +
	"\fcollector_id\x18\n" +
	" \x01(\tR\vcollectorId\x12\x1c\n" +
	"\tfrequency\x18\v \x01(\x03R\tfrequency\"\xb9\x01\n" +
	"\x13SketchInputResponse\x12-\n" +
	"\x04data\x18\x01 \x01(\v2\x17.queryproto.SketchInputH\x00R\x04data\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x19.queryproto.ErrorResponseH\x00R\x05error\x124\n" +
	"\x04done\x18\x03 \x01(\v2\x1e.queryproto.CompletionResponseH\x00R\x04doneB\n" +
	"\n" +
	"\bresponse\"\xc4\x01\n" +
	"\vSketchInput\x12\x17\n" +
	"\aexpr_id\x18\x01 \x01(\tR\x06exprId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x03R\tfrequency\x127\n" +
	"\vsketch_tags\x18\x05 \x01(\v2\x16.queryproto.SketchTagsR\n" +
	"sketchTags\"{\n" +
	"\n" +
	"SketchTags\x124\n" +
	"\x04tags\x18\x01 \x03(\v2 .queryproto.SketchTags.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\",\n" +
	"\x12CompletionResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice2\xa1\x01\n" +
	"\vQueryWorker\x12Q\n" +
	"\x0fProcessPushdown\x12\x1b.queryproto.PushDownRequest\x1a\x1f.queryproto.SketchInputResponse0\x01\x12?\n" +
	"\x06Health\x12\x19.queryproto.HealthRequest\x1a\x1a.queryproto.HealthResponseB-Z+github.com/cardinalhq/lakerunner/queryprotob\x06proto3"

var (
	file_queryworker_proto_rawDescOnce sync.Once
	file_queryworker_proto_rawDescData []byte
)

func file_queryworker_proto_rawDescGZIP() []byte {
	file_queryworker_proto_rawDescOnce.Do(func() {
		file_queryworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queryworker_proto_rawDesc), len(file_queryworker_proto_rawDesc)))
	})
	return file_queryworker_proto_rawDescData
}

var file_queryworker_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_queryworker_proto_goTypes = []any{
	(*PushDownRequest)(nil),     // 0: queryproto.PushDownRequest
	(*BaseExpr)(nil),            // 1: queryproto.BaseExpr
	(*LabelMatch)(nil),          // 2: queryproto.LabelMatch
	(*SegmentInfo)(nil),         // 3: queryproto.SegmentInfo
	(*SketchInputResponse)(nil), // 4: queryproto.SketchInputResponse
	(*SketchInput)(nil),         // 5: queryproto.SketchInput
	(*SketchTags)(nil),          // 6: queryproto.SketchTags
	(*ErrorResponse)(nil),       // 7: queryproto.ErrorResponse
	(*CompletionResponse)(nil),  // 8: queryproto.CompletionResponse
	(*HealthRequest)(nil),       // 9: queryproto.HealthRequest
	(*HealthResponse)(nil),      // 10: queryproto.HealthResponse
	nil,                         // 11: queryproto.SketchTags.TagsEntry
}
var file_queryworker_proto_depIdxs = []int32{
	1,  // 0: queryproto.PushDownRequest.base_expr:type_name -> queryproto.BaseExpr
	3,  // 1: queryproto.PushDownRequest.segments:type_name -> queryproto.SegmentInfo
	2,  // 2: queryproto.BaseExpr.matchers:type_name -> queryproto.LabelMatch
	5,  // 3: queryproto.SketchInputResponse.data:type_name -> queryproto.SketchInput
	7,  // 4: queryproto.SketchInputResponse.error:type_name -> queryproto.ErrorResponse
	8,  // 5: queryproto.SketchInputResponse.done:type_name -> queryproto.CompletionResponse
	6,  // 6: queryproto.SketchInput.sketch_tags:type_name -> queryproto.SketchTags
	11, // 7: queryproto.SketchTags.tags:type_name -> queryproto.SketchTags.TagsEntry
	0,  // 8: queryproto.QueryWorker.ProcessPushdown:input_type -> queryproto.PushDownRequest
	9,  // 9: queryproto.QueryWorker.Health:input_type -> queryproto.HealthRequest
	4,  // 10: queryproto.QueryWorker.ProcessPushdown:output_type -> queryproto.SketchInputResponse
	10, // 11: queryproto.QueryWorker.Health:output_type -> queryproto.HealthResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_queryworker_proto_init() }
func file_queryworker_proto_init() {
	if File_queryworker_proto != nil {
		return
	}
	file_queryworker_proto_msgTypes[4].OneofWrappers = []any{
		(*SketchInputResponse_Data)(nil),
		(*SketchInputResponse_Error)(nil),
		(*SketchInputResponse_Done)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queryworker_proto_rawDesc), len(file_queryworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queryworker_proto_goTypes,
		DependencyIndexes: file_queryworker_proto_depIdxs,
		MessageInfos:      file_queryworker_proto_msgTypes,
	}.Build()
	File_queryworker_proto = out.File
	file_queryworker_proto_goTypes = nil
	file_queryworker_proto_depIdxs = nil
}
