-- 1755703819_add_organizations_table.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- Organizations table that we sync from c_organizations
CREATE TABLE lrconfig_organizations (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for name lookups  
CREATE INDEX idx_lrconfig_organizations_name ON lrconfig_organizations(name);

-- Index for enabled lookups
CREATE INDEX idx_lrconfig_organizations_enabled ON lrconfig_organizations(enabled);

