-- 1755582182_bucket_management_tables.down.sql

-- Code generated by database migration. DO NOT EDIT.


-- Drop tables in reverse order (respecting foreign key dependencies)
DROP TABLE IF EXISTS lrconfig_bucket_prefix_mappings;
DROP TABLE IF EXISTS lrconfig_organization_buckets;
DROP TABLE IF EXISTS lrconfig_bucket_configurations;
