-- 1755706737_add_s3_connection_flags.up.sql

-- Code generated by database migration. DO NOT EDIT.


-- Add S3 connection configuration flags to bucket configurations
ALTER TABLE lrconfig_bucket_configurations 
ADD COLUMN use_path_style BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN insecure_tls BOOLEAN NOT NULL DEFAULT FALSE;