-- 1756530538_add_provider_config_to_bucket_configurations.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- Add provider configuration columns to bucket_configurations table
ALTER TABLE bucket_configurations
ADD COLUMN IF NOT EXISTS provider_type TEXT DEFAULT 'aws' NOT NULL,
ADD COLUMN IF NOT EXISTS provider_config JSONB DEFAULT '{}' NOT NULL;

-- Create index on provider_type for efficient queries
CREATE INDEX IF NOT EXISTS idx_bucket_configurations_provider_type
ON bucket_configurations(provider_type);

-- Add check constraint for valid provider types
ALTER TABLE bucket_configurations
ADD CONSTRAINT chk_provider_type
CHECK (provider_type IN ('aws', 'gcp', 'azure', 'local'));
