apiVersion: v1
kind: ServiceAccount
metadata:
  name: lakerunner
  labels:
    app.kubernetes.io/name: lakerunner
    app.kubernetes.io/component: lakerunner-serviceaccount
    app.kubernetes.io/part-of: lakerunner
