apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
stringData:
  METADATADB_URL: 'postgres://USER:PASSWORD@HOSTNAME/metadata'
  POSTGRES_HOST: 'HOSTNAME'
  POSTGRES_PORT: '5432'
  POSTGRES_USER: 'USERNAME'
  POSTGRES_PASSWORD: 'PASSWORD'
