-- 1755796719_add_inqueue_file_size.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- NOTE: This migration previously modified the inqueue table which has since been dropped
-- ALTER TABLE inqueue ADD COLUMN file_size BIGINT NOT NULL DEFAULT -1;
