-- 1755805001_obj_cleanup_bucket_delete_index.up.sql

-- Code generated by database migration. DO NOT EDIT.

CREATE INDEX IF NOT EXISTS idx_obj_cleanup_bucket_delete
  ON obj_cleanup (bucket_id, delete_at);
