-- 1756775340_queue-availability.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- Add eligibility column to both queues
ALTER TABLE public.metric_compaction_queue
  ADD COLUMN IF NOT EXISTS eligible_at timestamptz NOT NULL DEFAULT now();

ALTER TABLE public.metric_rollup_queue
  ADD COLUMN IF NOT EXISTS eligible_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS mcq_ready_idx
ON public.metric_compaction_queue (priority, eligible_at, queue_ts)
INCLUDE (organization_id, dateint, frequency_ms, instance_num, record_count)
WHERE claimed_by = -1;

CREATE INDEX IF NOT EXISTS mrq_ready_idx
ON public.metric_rollup_queue (priority, eligible_at, window_close_ts, queue_ts)
INCLUDE (organization_id, dateint, frequency_ms, instance_num, slot_id, slot_count, record_count)
WHERE claimed_by = -1;

-- For reclaiming timed-out work quickly
CREATE INDEX IF NOT EXISTS mcq_claimed_hb_idx
  ON public.metric_compaction_queue (heartbeated_at)
  WHERE claimed_by <> -1;

CREATE INDEX IF NOT EXISTS mrq_claimed_hb_idx
  ON public.metric_rollup_queue (heartbeated_at)
  WHERE claimed_by <> -1;
