-- 1756680861_fix_metric_rollup_queue_record_count_constraints.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- NOTE: Removed operations on metric_rollup_queue since table is later dropped

-- Remove default value from record_count column (check constraint already exists from previous migration)
-- ALTER TABLE metric_rollup_queue ALTER COLUMN record_count DROP DEFAULT;