-- 1756677163_fix_metric_rollup_queue_structure.down.sql

-- Code generated by database migration. DO NOT EDIT.

-- Remove the record_count constraint
ALTER TABLE metric_rollup_queue 
    DROP CONSTRAINT IF EXISTS chk_mrq_record_count_positive;

-- Remove record_count column
ALTER TABLE metric_rollup_queue DROP COLUMN IF EXISTS record_count;

-- Add back ts_range column
ALTER TABLE metric_rollup_queue ADD COLUMN IF NOT EXISTS ts_range TSTZRANGE;