-- 1756587525_add_record_count_check_to_mcq.down.sql

-- Code generated by database migration. DO NOT EDIT.

-- Remove check constraint for record_count
ALTER TABLE metric_compaction_queue 
DROP CONSTRAINT chk_mcq_record_count_positive;

