-- 1756559906_update_inqueue_indexes_and_signal_column.down.sql

-- Code generated by database migration. DO NOT EDIT.

-- Drop new indexes
DROP INDEX IF EXISTS idx_inqueue_ready_bigfile;
DROP INDEX IF EXISTS idx_inqueue_ready_group;

-- Remove check constraint and rename column back
ALTER TABLE inqueue DROP CONSTRAINT IF EXISTS chk_inqueue_signal;
ALTER TABLE inqueue RENAME COLUMN signal TO telemetry_type;

-- Recreate old index
CREATE INDEX IF NOT EXISTS idx_inqueue_pri_ts
ON inqueue (priority DESC, queue_ts)
WHERE claimed_at IS NULL;

