-- 1756688947_add_rollup_group_to_metric_rollup_queue.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- NOTE: metric_rollup_queue table has since been dropped, but keeping DELETE as it's harmless
-- Delete all existing rows since we can't populate the new non-null column
DELETE FROM metric_rollup_queue;

-- Add rollup_group column that represents the rollup time grouping
-- This is calculated as segment's start time / target rollup frequency
-- ALTER TABLE metric_rollup_queue ADD COLUMN rollup_group BIGINT NOT NULL;

-- Add constraint that rollup_group must be > 0
-- ALTER TABLE metric_rollup_queue
--     ADD CONSTRAINT chk_mrq_rollup_group_positive CHECK (rollup_group > 0);

-- Update the per-group index to include rollup_group for grouping
-- DROP INDEX IF EXISTS idx_mrq_ready_group;
-- CREATE INDEX idx_mrq_ready_group
-- ON metric_rollup_queue (
--   organization_id, dateint, frequency_ms, instance_num, slot_id, slot_count, rollup_group,
--   priority DESC, queue_ts, id
-- )
-- WHERE claimed_at IS NULL;