-- 1757271620_drop_metric_rollup_queue.up.sql

-- Code generated by database migration. DO NOT EDIT.

-- Drop the metric_rollup_queue table and all its indexes
DROP TABLE IF EXISTS metric_rollup_queue CASCADE;