-- 1757218490_drop_metric_compaction_queue.down.sql

-- Code generated by database migration. DO NOT EDIT.

-- This is a one-way migration. The metric_compaction_queue table cannot be restored.
-- No-op
