-- 1758318204_add_pubsub_message_history.up.sql

-- Code generated by database migration. DO NOT EDIT.

CREATE TABLE pubsub_message_history (
    organization_id UUID NOT NULL,
    instance_num SMALLINT NOT NULL,
    bucket TEXT NOT NULL,
    object_id TEXT NOT NULL,
    source TEXT NOT NULL,  -- 'sqs', 'gcp', 'azure', 'http'
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (organization_id, instance_num, bucket, object_id, source)
);

CREATE INDEX idx_pubsub_history_received_at ON pubsub_message_history(received_at);
