name: Build Release Candidate

on:
  push:
    tags:
      - 'v*.*.*-rc*'

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  partials:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux_amd64
            label: ubuntu-22.04
            cache_path: dist/linux_amd64
          - name: linux_arm64
            label: ubuntu-22.04-arm
            cache_path: dist/linux_arm64
    runs-on: ${{ matrix.label }}
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      # Native builds on correct arch — no QEMU needed
      - uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ secrets.ECR_ACCOUNT_ID }}:role/${{ secrets.ECR_ROLE_NAME }}
          aws-region: ${{ secrets.ECR_REGISTRY_REGION }}
          role-session-name: GitHubActions

      - name: Login to PUBLIC Amazon ECR
        env:
          AWS_REGION: us-east-1
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: ${{ matrix.cache_path }}
          key: ${{ matrix.name }}-${{ env.sha_short }}

      - shell: bash
        run: make clean

      - name: Build custom build environment
        run: docker build -f Dockerfile.build -t lakerunner-build .

      - name: Run GoReleaser Pro in custom container
        run: |
          DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
          docker run --rm \
            -v $PWD:/workspace \
            -v $PWD/.git:/workspace/.git \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            --user 1001:$DOCKER_GID \
            -e GORELEASER_KEY="${{ secrets.GORELEASER_KEY }}" \
            -e GORELEASER_CURRENT_TAG="${{ github.ref_name }}" \
            -e AWS_ACCESS_KEY_ID="${{ env.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_ACCESS_KEY="${{ env.AWS_SECRET_ACCESS_KEY }}" \
            -e AWS_SESSION_TOKEN="${{ env.AWS_SESSION_TOKEN }}" \
            -e AWS_REGION="${{ env.AWS_REGION }}" \
            lakerunner-build \
            release --clean --split --config .goreleaser.rc.yaml

      - shell: bash
        run: ls -lR dist

  merge:
    needs: partials
    runs-on: ubuntu-22.04
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3
      - uses: sigstore/cosign-installer@v3.9.2
      - uses: anchore/sbom-action/download-syft@v0.20.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ secrets.ECR_ACCOUNT_ID }}:role/${{ secrets.ECR_ROLE_NAME }}
          aws-region: ${{ secrets.ECR_REGISTRY_REGION }}
          role-session-name: GitHubActions

      - name: Login to PUBLIC Amazon ECR
        env:
          AWS_REGION: us-east-1
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - shell: bash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: dist/linux_amd64
          key: linux_amd64-${{ env.sha_short }}
          fail-on-cache-miss: true

      - uses: actions/cache@v4
        with:
          path: dist/linux_arm64
          key: linux_arm64-${{ env.sha_short }}
          fail-on-cache-miss: true

      - name: Setup GoReleaser Pro
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser-pro
          version: '~> v2'
          install-only: true
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: Run GoReleaser Pro merge
        run: goreleaser continue --merge
        env:
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
          GORELEASER_CURRENT_TAG: ${{ github.ref_name }}

      - name: Output built images
        run: |
          echo "Release Candidate built successfully!"
          echo "Image: public.ecr.aws/cardinalhq.io/lakerunner:${{ github.ref_name }}"
          echo ""
          echo "Testing this RC before promotion:"
          echo "  1. Deploy to staging environment"
          echo "  2. Run integration tests"
          echo "  3. Validate functionality"
          echo ""
          echo "To promote to production, use the 'Promote Release' workflow"
