name: Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "29.x"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install protoc Go plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - name: Test
      run: make check
